stages:
  - build
  - test
  - deploy

build_backend:
  stage: build
  image: python:3
  script:
    - cd backend
    - pip install --upgrade pip  # Upgrade pip
    - pip install --no-cache-dir -r requirements.txt
    - python manage.py collectstatic --noinput  # Collect static files without interactive prompts
    - python manage.py migrate  # Apply database migrations

build_frontend:
  stage: build
  image: node:14
  script:
    - cd frontend
    - npm install -g npm@
    - npm install --force
    - npm run build  # Build the React app
