stages:
  - build
  - test
  - deploy

variables:
  DATABASE_URL: "postgresql://postgres:123456@db:5432/house_owner"

build_backend:
  stage: build
  image: python:3
  script:
    - cd backend
    - pip install --upgrade pip  # Upgrade pip
    - pip3 install virtualenv
    - virtualenv -p python3 venv
    - source venv/bin/activate
    - pip install --no-cache-dir -r requirements.txt
    # Set up and run tests
    - python3 manage.py makemigrations 
    - python3 manage.py migrate

build_frontend:
  stage: build
  image: node:14
  script:
    - cd frontend
    - npm install -g npm@
    - npm install --force
    - npm run build  # Build the React app
