version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"  
    restart: always
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=house_owner
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - /postgres_data:/var/lib/postgresql/data

