# Generated by Django 4.2 on 2023-04-24 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("realtor", models.EmailField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("zipcode", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("area", models.DecimalField(decimal_places=1, max_digits=3)),
                ("bedrooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                (
                    "home_type",
                    models.CharField(
                        choices=[
                            ("House", "House"),
                            ("Condo", "Condo"),
                            ("Townhouse", "Townhouse"),
                        ],
                        default="House",
                        max_length=10,
                    ),
                ),
                ("main_photo", models.ImageField(upload_to="listings/")),
                ("photo1", models.ImageField(upload_to="listings/")),
                ("photo2", models.ImageField(upload_to="listings/")),
                ("photo3", models.ImageField(upload_to="listings/")),
                ("photo4", models.ImageField(upload_to="listings/")),
                ("is_published", models.BooleanField(default=False)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
