# Generated by Django 4.2 on 2023-04-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
