export const LISTING_LIST_REQUEST = "LISTING_LIST_REQUEST";
export const LISTING_LIST_SUCCESS = "LISTING_LIST_SUCCESS";
export const LISTING_LIST_FAIL = "LISTING_LIST_FAIL";

export const LISTING_DETAILS_REQUEST = "LISTING_DETAILS_REQUEST";
export const LISTING_DETAILS_SUCCESS = "LISTING_DETAILS_SUCCESS";
export const LISTING_DETAILS_FAIL = "LISTING_DETAILS_FAIL";

export const LISTING_DELETE_REQUEST = "LISTING_DELETE_REQUEST";
export const LISTING_DELETE_SUCCESS = "LISTING_DELETE_SUCCESS";
export const LISTING_DELETE_FAIL = "LISTING_DELETE_FAIL";

export const LISTING_CREATE_REQUEST = "LISTING_CREATE_REQUEST";
export const LISTING_CREATE_SUCCESS = "LISTING_CREATE_SUCCESS";
export const LISTING_CREATE_FAIL = "LISTING_CREATE_FAIL";
export const LISTING_CREATE_RESET = "LISTING_CREATE_RESET";

export const LISTING_UPDATE_REQUEST = "LISTING_UPDATE_REQUEST";
export const LISTING_UPDATE_SUCCESS = "LISTING_UPDATE_SUCCESS";
export const LISTING_UPDATE_FAIL = "LISTING_UPDATE_FAIL";
export const LISTING_UPDATE_RESET = "LISTING_UPDATE_RESET";

export const LISTING_SEARCH_REQUEST = "LISTING_SEARCH_REQUEST";
export const LISTING_SEARCH_SUCCESS = "LISTING_SEARCH_SUCCESS";
export const LISTING_SEARCH_FAIL = "LISTING_SEARCH_FAIL";

// Constants for CRUD operations
export const LISTING_CREATE_ORDER_REQUEST = "LISTING_CREATE_ORDER_REQUEST";
export const LISTING_CREATE_ORDER_SUCCESS = "LISTING_CREATE_ORDER_SUCCESS";
export const LISTING_CREATE_ORDER_FAIL = "LISTING_CREATE_ORDER_FAIL";

export const LISTING_READ_ORDER_REQUEST = "LISTING_READ_ORDER_REQUEST";
export const LISTING_READ_ORDER_SUCCESS = "LISTING_READ_ORDER_SUCCESS";
export const LISTING_READ_ORDER_FAIL = "LISTING_READ_ORDER_FAIL";

export const LISTING_UPDATE_ORDER_REQUEST = "LISTING_UPDATE_ORDER_REQUEST";
export const LISTING_UPDATE_ORDER_SUCCESS = "LISTING_UPDATE_ORDER_SUCCESS";
export const LISTING_UPDATE_ORDER_FAIL = "LISTING_UPDATE_ORDER_FAIL";

export const LISTING_DELETE_ORDER_REQUEST = "LISTING_DELETE_ORDER_REQUEST";
export const LISTING_DELETE_ORDER_SUCCESS = "LISTING_DELETE_ORDER_SUCCESS";
export const LISTING_DELETE_ORDER_FAIL = "LISTING_DELETE_ORDER_FAIL";
