# Generated by Django 4.2 on 2023-05-15 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="auth_provider",
            field=models.CharField(default="email", max_length=255),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useraccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
