# Generated by Django 4.2 on 2023-05-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="phone_contact",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="view_counts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="listing",
            name="area",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="listing",
            name="main_photo",
            field=models.ImageField(
                default="listings/placeholder.jpg", upload_to="listings/"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo1",
            field=models.ImageField(
                default="listings/placeholder.jpg", upload_to="listings/"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo2",
            field=models.ImageField(
                default="listings/placeholder.jpg", upload_to="listings/"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo3",
            field=models.ImageField(
                default="listings/placeholder.jpg", upload_to="listings/"
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo4",
            field=models.ImageField(
                default="listings/placeholder.jpg", upload_to="listings/"
            ),
        ),
    ]
