# Generated by Django 4.2 on 2023-05-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_listing_phone_contact_listing_view_counts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="property_status",
            field=models.CharField(
                choices=[
                    ("House", "House"),
                    ("Condo", "Condo"),
                    ("Townhouse", "Townhouse"),
                ],
                default="Other",
                max_length=10,
            ),
        ),
    ]
