# Generated by Django 4.2 on 2023-05-24 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_listing_property_status"),
    ]

    operations = [
        migrations.RemoveField(model_name="listing", name="photo1",),
        migrations.RemoveField(model_name="listing", name="photo2",),
        migrations.RemoveField(model_name="listing", name="photo3",),
        migrations.RemoveField(model_name="listing", name="photo4",),
        migrations.CreateModel(
            name="ListingsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="listings")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="base.listing",
                    ),
                ),
            ],
        ),
    ]
