# Generated by Django 4.2 on 2023-05-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_remove_listing_photo1_remove_listing_photo2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="main_photo",
            field=models.ImageField(
                default="/listings/placeholder.jpg", upload_to="listings"
            ),
        ),
    ]
