# Generated by Django 4.2 on 2023-05-30 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_useraccount_image_url_alter_listing_main_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.listing"
            ),
        ),
    ]
