# Generated by Django 4.2 on 2023-06-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_remove_listing_base_listin_realtor_e00890_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["realtor"], name="base_listin_realtor_e00890_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["city"], name="base_listin_city_id_67cd3c_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["district"], name="base_listin_distric_647611_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["price"], name="base_listin_price_140c11_idx"),
        ),
        migrations.AddIndex(
            model_name="useraccount",
            index=models.Index(fields=["email"], name="base_userac_email_d9cfe3_idx"),
        ),
        migrations.AddIndex(
            model_name="useraccount",
            index=models.Index(fields=["name"], name="base_userac_name_7e48b5_idx"),
        ),
    ]
